name: cached and install dependencies
description: 'cache and install dependencies (npm) '
inputs:
  caching:
    description: specify if you want use cache or not
    required: false
    default: 'true'
runs:
 using: 'composite'
 steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' 
      run: npm ci
      shell: bash

